# Generated by Django 3.2.13 on 2023-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('duraçao', models.CharField(max_length=50, null=True)),
                ('genero', models.CharField(max_length=30, null=True)),
                ('preço', models.CharField(max_length=30, null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('zona', models.CharField(max_length=50, null=True)),
                ('insta', models.CharField(max_length=30, null=True)),
                ('tipo', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trilhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('zona', models.CharField(choices=[('N', 'Norte'), ('S', 'Sul'), ('L', 'Leste'), ('O', 'Oeste')], max_length=50, null=True)),
                ('nivel', models.CharField(choices=[('F', 'Facil'), ('M', 'Medio'), ('D', 'Dificil')], max_length=1, null=True)),
                ('mais_famosa', models.IntegerField(null=True)),
            ],
        ),
    ]
